import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-geist-sans)', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'ui-monospace', 'SF Mono', 'Menlo', 'Monaco', 'monospace'],
      },
      // Weights follow §5: 600 headings, 500 interactive, 400 reading. Never 700.
      // Tracking tightens as size grows.
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-2.4px', fontWeight: '600' }],
        display: ['32px', { lineHeight: '40px', letterSpacing: '-1.28px', fontWeight: '600' }],
        h1: ['24px', { lineHeight: '32px', letterSpacing: '-0.96px', fontWeight: '600' }],
        h2: ['20px', { lineHeight: '26px', letterSpacing: '-0.4px', fontWeight: '600' }],
        h3: ['16px', { lineHeight: '24px', letterSpacing: '-0.32px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        body: ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        button: ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      zIndex: {
        base: 'var(--z-base)',
        sticky: 'var(--z-sticky)',
        savebar: 'var(--z-savebar)',
        sidebar: 'var(--z-sidebar)',
        topbar: 'var(--z-topbar)',
        dropdown: 'var(--z-dropdown)',
        'drawer-backdrop': 'var(--z-drawer-backdrop)',
        drawer: 'var(--z-drawer)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
        command: 'var(--z-command)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        glow: 'var(--shadow-glow)',
      },
      backgroundImage: {
        'panel-gradient': 'linear-gradient(135deg, var(--panel-gradient-1) 0%, var(--panel-gradient-2) 50%, var(--panel-gradient-3) 100%)',
        'hero-gradient': 'linear-gradient(to right, var(--hero-from), var(--hero-via), var(--hero-to))',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        surface: 'var(--surface)',
        'surface-foreground': 'var(--surface-foreground)',
        'surface-2': 'var(--surface-2)',
        'surface-hover': 'var(--surface-hover)',
        'surface-sunken': 'var(--surface-sunken)',
        overlay: 'var(--overlay)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        heading: 'var(--heading)',
        bodyText: 'var(--body)',
        muted: 'var(--muted)',
        'muted-bg': 'var(--muted-bg)',
        'muted-foreground': 'var(--muted-foreground)',
        'text-3': 'var(--text-3)',
        'text-4': 'var(--text-4)',
        'text-disabled': 'var(--text-disabled)',
        'text-inverse': 'var(--text-inverse)',
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
          active: 'var(--primary-active)',
          ink: 'var(--primary-ink)',
          soft: 'var(--primary-soft)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        'accent-ai': {
          DEFAULT: 'var(--accent-ai)',
          hover: 'var(--accent-ai-hover)',
        },
        ai: {
          DEFAULT: 'var(--ai)',
          hover: 'var(--ai-hover)',
          pressed: 'var(--ai-pressed)',
          ink: 'var(--ai-ink)',
          'ink-strong': 'var(--ai-ink-strong)',
          wash: 'var(--ai-wash)',
          'wash-2': 'var(--ai-wash-2)',
          border: 'var(--ai-border)',
        },
        jobs: {
          DEFAULT: 'var(--jobs-base)',
          ink: 'var(--jobs-ink)',
          'ink-strong': 'var(--jobs-ink-strong)',
          wash: 'var(--jobs-wash)',
          'wash-2': 'var(--jobs-wash-2)',
          border: 'var(--jobs-border)',
        },
        candidates: {
          DEFAULT: 'var(--candidates-base)',
          ink: 'var(--candidates-ink)',
          'ink-strong': 'var(--candidates-ink-strong)',
          wash: 'var(--candidates-wash)',
          'wash-2': 'var(--candidates-wash-2)',
          border: 'var(--candidates-border)',
        },
        interviews: {
          DEFAULT: 'var(--interviews-base)',
          ink: 'var(--interviews-ink)',
          'ink-strong': 'var(--interviews-ink-strong)',
          wash: 'var(--interviews-wash)',
          'wash-2': 'var(--interviews-wash-2)',
          border: 'var(--interviews-border)',
        },
        reports: {
          DEFAULT: 'var(--reports-base)',
          ink: 'var(--reports-ink)',
          'ink-strong': 'var(--reports-ink-strong)',
          wash: 'var(--reports-wash)',
          'wash-2': 'var(--reports-wash-2)',
          border: 'var(--reports-border)',
        },
        settings: {
          DEFAULT: 'var(--settings-base)',
          ink: 'var(--settings-ink)',
          'ink-strong': 'var(--settings-ink-strong)',
          wash: 'var(--settings-wash)',
          'wash-2': 'var(--settings-wash-2)',
          border: 'var(--settings-border)',
        },
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
          6: 'var(--chart-6)',
          ai: 'var(--chart-ai)',
          grid: 'var(--chart-grid)',
          'axis-line': 'var(--chart-axis-line)',
          'seq-1': 'var(--chart-seq-1)',
          'seq-2': 'var(--chart-seq-2)',
          'seq-3': 'var(--chart-seq-3)',
          'seq-4': 'var(--chart-seq-4)',
        },
        indigo: {
          900: 'var(--indigo-900)',
          700: 'var(--indigo-700)',
          500: 'var(--indigo-500)',
          300: 'var(--indigo-300)',
          100: 'var(--indigo-100)',
        },
        gray: {
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
          1000: 'var(--gray-1000)',
        },
        blue: {
          100: 'var(--blue-100)',
          200: 'var(--blue-200)',
          400: 'var(--blue-400)',
          700: 'var(--blue-700)',
          800: 'var(--blue-800)',
          900: 'var(--blue-900)',
        },
        red: {
          100: 'var(--red-100)',
          400: 'var(--red-400)',
          700: 'var(--red-700)',
          800: 'var(--red-800)',
          900: 'var(--red-900)',
        },
        amber: {
          100: 'var(--amber-100)',
          400: 'var(--amber-400)',
          700: 'var(--amber-700)',
          900: 'var(--amber-900)',
        },
        green: {
          100: 'var(--green-100)',
          400: 'var(--green-400)',
          700: 'var(--green-700)',
          900: 'var(--green-900)',
        },
        purple: {
          100: 'var(--purple-100)',
          400: 'var(--purple-400)',
          700: 'var(--purple-700)',
          900: 'var(--purple-900)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
          ink: 'var(--success-ink)',
          wash: 'var(--success-wash)',
          border: 'var(--success-border)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
          ink: 'var(--warning-ink)',
          wash: 'var(--warning-wash)',
          border: 'var(--warning-border)',
        },
        error: {
          DEFAULT: 'var(--error)',
          foreground: 'var(--error-foreground)',
          ink: 'var(--error-ink)',
          active: 'var(--error-active)',
          wash: 'var(--error-wash)',
          border: 'var(--error-border)',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: 'var(--info-foreground)',
          ink: 'var(--info-ink)',
          wash: 'var(--info-wash)',
          border: 'var(--info-border)',
        },
        'card-hover': 'var(--card-hover)',
        'active-menu-bg': 'var(--active-menu-bg)',
        'error-banner-bg': 'var(--error-banner-bg)',
        'success-toast-bg': 'var(--success-toast-bg)',
        /* shadcn compatibility aliases */
        card: {
          DEFAULT: 'var(--surface)',
          foreground: 'var(--surface-foreground)',
        },
        popover: {
          DEFAULT: 'var(--surface)',
          foreground: 'var(--surface-foreground)',
        },
        accent: {
          DEFAULT: 'var(--active-menu-bg)',
          foreground: 'var(--primary)',
        },
        destructive: {
          DEFAULT: 'var(--error)',
          foreground: 'var(--error-foreground)',
        },
        'muted-token': 'var(--muted)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'float-delayed': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '0.8' },
          '100%': { transform: 'scale(2.4)', opacity: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.4s ease-out',
        'slide-in-right': 'slide-in-right 0.5s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float-delayed 7s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 8s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 2.5s ease-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
