/** Curated city list backing the location place-search mock, same style as timezones.ts/languages.ts. */
export const CITIES: string[] = [
  'Amsterdam, Netherlands',
  'Austin, TX, USA',
  'Bangalore, India',
  'Barcelona, Spain',
  'Berlin, Germany',
  'Boston, MA, USA',
  'Chicago, IL, USA',
  'Copenhagen, Denmark',
  'Dubai, UAE',
  'Dublin, Ireland',
  'London, UK',
  'Los Angeles, CA, USA',
  'Madrid, Spain',
  'Manchester, UK',
  'Melbourne, Australia',
  'Mexico City, Mexico',
  'Mumbai, India',
  'New York, NY, USA',
  'Paris, France',
  'San Francisco, CA, USA',
  'Sao Paulo, Brazil',
  'Seattle, WA, USA',
  'Singapore',
  'Stockholm, Sweden',
  'Sydney, Australia',
  'Tokyo, Japan',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Warsaw, Poland',
  'Zurich, Switzerland',
];
